sudo: required
services:
    - docker

before_install:
    - docker build -t wall05/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run wall05/react-test npm test -- --coverage

after_success:    
    
    - docker build -t wall05/multi-server ./server
    - docker build -t wall05/multi-worker ./worker
    - docker build -t wall05/multi-client ./client
    - docker build -t wall05/multi-nginx ./nginx
    
    # # Login to docker cli
    # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # # push images to docker
    # - docker push wall05/multi-client
    # - docker push wall05/multi-nginx
    # - docker push wall05/multi-server
    # - docker push wall05/multi-worker
