sudo: required

services:
    - docker

before_install:
    - docker build -t wall05/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true wall05/react-test npm test

after_success:   
    - docker build -t wall05/multi-client ./client
    - docker build -t wall05/multi-nginx ./nginx
    - docker build -t wall05/multi-server ./server
    - docker build -t wall05/multi-worker ./worker
    
    # # Login to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # # push images to docker
    - docker push wall05/multi-client
    - docker push wall05/multi-nginx
    - docker push wall05/multi-server
    - docker push wall05/multi-worker
