sudo: required
services:
    - docker

before_install:
    - docker build -t robertaustin/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run robertaustin/react-test npm test -- --coverage

after_success:
    - docker build -t robertaustin/multi-client ./client
    - docker build -t robertaustin/multi-nginx ./nginx
    - docker build -t robertaustin/multi-server ./server
    - docker build -t robertaustin/multi-worker ./worker
    
    # Login to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # push images to docker
    - docker push robertaustin/multi-client
    - docker push robertaustin/multi-nginx
    - docker push robertaustin/multi-server
    - docker push robertaustin/multi-worker
